### ISSUE TITLE
Error thrown when property has null value

### ISSUE THREAD

**Issue by eheikes** [strikeentco/get#1]
Not sure if this is a bug or a undocumented gotcha, but any property with a value of `null` will throw an error if you try to access a subproperty:

```javascript
const get = require('@strikeentco/get');
get({ a: null }, 'a.b'); // TypeError: Cannot read property 'b' of null
```

It would be nice to return `undefined` if this is the case.

**Comment by strikeentco** [comment]
It was definitely a bug.
![Thank you](https://media.giphy.com/media/3oz8xIsloV7zOmt81G/giphy.gif)
